### ISSUE TITLE
您好 想问一下这个项目测试过确定可以下载吗？我没有下载下来。

### ISSUE THREAD

**Issue by liujie316316** [Jwtcode/BaiduDiskAI_DocImageSuperResolution_top1#1]

**Comment by Jwtcode** [comment]
如果您使用的是国内网，请确定一下您的VPN是否工作

**Comment by liujie316316** [comment]
> 如果您使用的是国内网，请确定一下您的VPN是否工作
您好，我的VPN在工作，而且下载其他的项目是可以下载的，也可以解压，但是这个项目下载下来之后解压会报错。显示文件已损坏不可解压。
